import type { YamaEntities, EntityDefinition, EntityField } from "../../entities.js";
import { normalizeEntityDefinition } from "../../entities.js";
import type { DatabaseIR, TableIR, ColumnIR, IndexIR, DBColumnType } from "./ir.js";

/**
 * Generate Database IR from Yama Entities configuration
 */
export function generateDatabaseIR(entities: YamaEntities): DatabaseIR {
    const tableIRs: TableIR[] = [];

    for (const [entityName, entityDef] of Object.entries(entities)) {
        const normalized = normalizeEntityDefinition(entityName, entityDef, entities);

        const tableIR: TableIR = {
            name: normalized.table || entityName.toLowerCase() + 's',
            entityName: entityName,
            columns: [],
            indexes: [],
        };

        // Columns
        for (const [fieldName, field] of Object.entries(normalized.fields)) {
            const column = mapFieldToColumn(fieldName, field, normalized, entities);
            if (column) {
                tableIR.columns.push(column);
            }
        }

        // Indexes from entity definition
        if (normalized.indexes) {
            for (const index of normalized.indexes) {
                tableIR.indexes.push({
                    name: index.name,
                    columns: index.fields.map(f => {
                        const field = normalized.fields[f];
                        return field?.dbColumn || f;
                    }),
                    unique: index.unique,
                });
            }
        }

        // Explicit field indexes
        for (const [fieldName, field] of Object.entries(normalized.fields)) {
            if (field.index && !field.primary) {
                tableIR.indexes.push({
                    columns: [field.dbColumn || fieldName],
                });
            }
        }

        tableIRs.push(tableIR);
    }

    return { tables: tableIRs };
}

function mapFieldToColumn(
    fieldName: string,
    field: EntityField,
    normalized: ReturnType<typeof normalizeEntityDefinition>,
    entities: YamaEntities
): ColumnIR | null {
    // Inline relations are handled via foreign keys generated by normalizeEntityDefinition
    // which show up as "fieldNameId" in normalized.fields
    if (field._isInlineRelation) {
        return null;
    }

    const column: ColumnIR = {
        name: field.dbColumn || fieldName,
        fieldName: fieldName,
        type: mapToDBType(field.type),
        dbType: field.dbType,
        primary: field.primary,
        unique: field.unique,
        nullable: field.nullable,
        default: field.default,
        generated: field.generated,
        length: (field as any).length,
        precision: (field as any).precision,
        scale: (field as any).scale,
    };

    // Check if this is an auto-generated foreign key from normalizeEntityDefinition
    const relation = Object.values(normalized.relations || {}).find(r => r.foreignKey === fieldName);
    if (relation) {
        const targetEntity = entities[relation.entity];
        const targetTable = targetEntity?.table || relation.entity.toLowerCase() + 's';

        column.references = {
            table: targetTable,
            column: 'id', // Default to 'id' for now, should eventually use primary key of target
            onDelete: relation.onDelete,
        };
    }

    return column;
}

function mapToDBType(type: string): DBColumnType {
    switch (type) {
        case "uuid": return "uuid";
        case "string": return "varchar";
        case "text": return "text";
        case "integer":
        case "int":
        case "int8":
        case "int16":
        case "int32":
        case "int64":
        case "uint":
            return "integer";
        case "bigint": return "bigint";
        case "boolean": return "boolean";
        case "timestamp":
        case "datetime":
            return "timestamp";
        case "timestamptz":
        case "datetimetz":
            return "timestamptz";
        case "date": return "date";
        case "time": return "time";
        case "json":
        case "jsonb":
            return "jsonb";
        case "decimal":
        case "money":
        case "float":
        case "double":
            return "decimal";
        default:
            return "text";
    }
}
